matrix:
  include:
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode12.5
      language: node_js
      node_js: "12"
      jdk: oraclejdk8
      script: npm run ci-ios && npm run ci-android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo easy_install pip
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
